### ISSUE TITLE
problem with logon in steam

### ISSUE THREAD

**Issue by lparamonov** [rannmann/node-steam-trade-tutorial#4]
so the problem is that  I installed node.js and steams libraries in my windows env as well. when u try to run server.js it throws exception:

TypeError: undefined is not a function
    at Object.<anonymous> (C:\Temp\server.js:76:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
lines 76 to 80 say
client.logOn({
    accountName: username, 
    password: password, 
    shaSentryfile: sentryfile // If null, a new Steam Guard code will be requested
});

**Comment by rannmann** [comment]
If you installed from this repo, everything should still work.  If you followed the guide instead, you're likely using `steam` v1.0 instead of 0.6.x.  The library has changed a lot in 1.0 and is not backward compatible.  You can remove `steam` via `npm uninstall steam` and reinstall it again using `npm install steam@0.6.8`.

I've updated the guide to use 0.6.8 and put a notice about the version change at the top of the article.

**Comment by lparamonov** [comment]
many thanks! that's helps as well. issue closed.
